"""Add file movement tracking

Revision ID: 56321f6c9724
Revises: 
Create Date: 2024-11-27 11:19:22.268868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56321f6c9724'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_movement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('from_department', sa.String(length=50), nullable=True),
    sa.Column('to_department', sa.String(length=50), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_movement')
    # ### end Alembic commands ###
